Multiplex/Controllers/MultiplexController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data.Context;
using Data.Entity;
using Data.Models;
using Multiplex.Factory;
using Multiplex.Factory.ModelPrepare;
using PagedList;
using ServiceLayer;
using ServiceLayer.Dropdown;

namespace Multiplex.Controllers
{
    public class MultiplexController : Controller
    {

        private readonly ICityService _cityService;
        private readonly IStateService _stateSevice;
        private readonly IMultiplexService _multiplexService;
        private readonly IMultiplexFactory _MultiplexFactory;
        private readonly IMultiplexModelFactory _multiplexModelFactory;

        public MultiplexController(IMultiplexService multiplexService, IMultiplexFactory MultiplexFactory, IStateService stateSevice,
                                    ICityService cityService, IMultiplexModelFactory multiplexModelFactory)
        {
            _multiplexModelFactory = multiplexModelFactory;
            _cityService = cityService;
            _stateSevice = stateSevice;
            _multiplexService = multiplexService;
            _MultiplexFactory = MultiplexFactory;
        }

        #region Multiplex

        public ActionResult Index(string searchString, int? page, string searchState, string searchCity)
        {
            var multiplex = _multiplexModelFactory.PrepareMultiplexModelForIndex(searchString, page, searchState, searchCity);
            ViewBag.state = new SelectList(_stateSevice.GetAllState().Where(X => X.IsDeleted == false), "Id", "Name");
            ViewBag.city = new SelectList(_cityService.GetAllCities().Where(X => X.IsDeleted == false), "Id", "Name");
            //ViewBag.CurrentFilter = searchString;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_IndexPartiaView", multiplex);
            }

            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            return View(multiplex);
        }

        public ActionResult MultiplexCreate()
        {
            ViewBag.state = new SelectList(_stateSevice.GetAllState().Where(X => X.IsDeleted == false), "Id", "Name");
            ViewBag.city = new SelectList(_cityService.GetAllCities().Where(X => X.IsDeleted == false), "Id", "Name");

            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            return PartialView("_CreatePartialView");
        }


        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(MultiplexModel model)
        {

            ViewBag.state = new SelectList(_stateSevice.GetAllState().Where(X => X.IsDeleted == false), "Id", "Name");
            ViewBag.city = new SelectList(_cityService.GetAllCities().Where(X => X.IsDeleted == false), "Id", "Name");
            if (ModelState.IsValid)
            {
                var multiplex = _MultiplexFactory.PrepareMultiplexModelToMultiplex(model);
                var check = _multiplexService.CheckData(multiplex);
                if (check == null)
                {
                    _multiplexService.InsertMultiplex(multiplex);
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView("_CreatePartialView", model);
        }

        public ActionResult EditMultiplexs(int multiplexId)
        {
            var multiplex = _multiplexModelFactory.PrepareMultiplexModelForEdit(multiplexId);

            ViewBag.state = new SelectList(_stateSevice.GetAllState().Where(X => X.IsDeleted == false), "Id", "Name");
            ViewBag.city = new SelectList(_cityService.GetAllCities().Where(X => X.IsDeleted == false), "Id", "Name");
            return PartialView("_EditPartialView", multiplex);
        }

        [HttpPost]
        public ActionResult Edit(MultiplexModel model)
        {
            ViewBag.state = new SelectList(_stateSevice.GetAllState().Where(X => X.IsDeleted == false), "Id", "Name");
            ViewBag.city = new SelectList(_cityService.GetAllCities().Where(X => X.IsDeleted == false), "Id", "Name");
            if (ModelState.IsValid)
            {
                _multiplexModelFactory.PrepareMultiplexModelForEditPost(model);
                return Json(true, JsonRequestBehavior.AllowGet);
            };

            var multiplex = _multiplexModelFactory.PrepareMultiplexModelForEdit(model.Id);
            return PartialView("_EditPartialView", model);
        }

        public ActionResult Delete(int id)
        {
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            _multiplexService.DeleteMultiplex(id);
            //TempData["Success"] = "Record Deleted successfully...!";
            return RedirectToAction("Index");

        }

        public ActionResult IndexPartialViewAsync(string searchString, int? page, string searchState, string searchCity)
        {
            var multiplex = _multiplexModelFactory.PrepareMultiplexModelForIndex(searchString, page, searchState, searchCity);
            ViewBag.CurrentFilter = searchString;

            return PartialView("_IndexPartiaView", multiplex);
        }

        #endregion
        public ActionResult ScreenList(int id)
        {
            return RedirectToAction("ScreenList", "Screen", new { multiplexId = id });
        }

        public ActionResult MovieList(int id)
        {
            return RedirectToAction("MovieMultiplexList", "Screen", new { multiplexId = id });
        }

        public ActionResult ShowList(int id)
        {
            return RedirectToAction("ShowList", "Screen", new { multiplexId = id });
        }
    }
}

Multiplex/Controllers/ScreenController.cs
using Data.Context;
using Data.Entity;
using Data.Models;
using Multiplex.Factory;
using Multiplex.Factory.ModelPrepare;
using ServiceLayer;
using ServiceLayer.Dropdown;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Multiplex.Controllers
{

    public class ScreenController : Controller
    {


        private readonly IShowPriceService _showPriceService;
        private readonly IShowService _showService;
        private readonly IFormateService _formateService;
        private readonly IMovieService _movieService;
        private readonly IMovie_Multiplex_Serviece _movieMultiplexServiece;
        private readonly ScreenService _screenService;
        private readonly SeatTypeService _seatTypeService;
        private readonly IMultiplexFactory _multiplexFactory;
        private readonly IScreenModelFactory _screenModelFactory;
        private readonly IDropDownListService _dropDownListService;

        public ScreenController(IShowService showService, ScreenService screenService, IMultiplexFactory multiplexFactory, IScreenModelFactory screenModelFactory,
                               IShowPriceService showPriceService, SeatTypeService seatTypeService, IMovie_Multiplex_Serviece movieMultiplexServiece,
                                IMovieService movieService, IFormateService formateService, IDropDownListService dropDownListService)
        {
            _showPriceService = showPriceService;
            _formateService = formateService;
            _movieService = movieService;
            _screenModelFactory = screenModelFactory;
            _movieMultiplexServiece = movieMultiplexServiece;
            _showService = showService;
            _seatTypeService = seatTypeService;
            _multiplexFactory = multiplexFactory;
            _screenService = screenService;
            _dropDownListService = dropDownListService;
        }
        #region Screen
        public ActionResult ScreenList(int multiplexId)
        {
            var screenList = _screenModelFactory.PrepareScreenModelForList(multiplexId);
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            return View(screenList);
        }

        public ActionResult CreateScreen(int id)
        {
            var screen = _screenModelFactory.PrepareScreenModelForCreateScreen(id);
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            return View(screen);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateScreen(ScreenModel model)
        {
            if (ModelState.IsValid)
            {
                var screen = _multiplexFactory.PrepareScreenModelToScreen(model);
                _screenService.InsertScreen(screen);
                TempData["Success"] = "Screen Created successfully...!";
                return RedirectToAction("ScreenList", new { multiplexId = model.MultiplexId });
            }
            return View();
        }

        public ActionResult EditScreen(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var screen = _screenModelFactory.PrepareScreenModelForEditScreen(id);
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            return View(screen);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditScreen(ScreenModel model)
        {
            if (ModelState.IsValid)
            {
                _screenModelFactory.PrepareScreenForEditPost(model);
                TempData["Success"] = "Screen Updated successfully...!";
                return RedirectToAction("ScreenList", new { multiplexId = model.MultiplexId });
            }
            return View();
        }

        public ActionResult DeleteScreen(int id)
        {
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            var screen = _screenService.GetScreenById(id);
            _screenService.DeleteScreen(id);
            TempData["AlertMessage"] = "Screen Deleted successfully...!";
            return RedirectToAction("ScreenList", new { multiplexId = screen.MultiplexId });

        }
        #endregion

        #region SeatType

        public ActionResult SeatTypeList(int ScreenId)
        {
            var seatType = _screenModelFactory.PrepareScreenListModelForList(ScreenId);

            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");

            return View(seatType);
        }

        public ActionResult CreateSeatType(int ScreenId)
        {
            var seatType = _screenModelFactory.PrepareSeatTypeModelForCreateSeatType(ScreenId);

            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");

            return View(seatType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSeatType(SeatTypeModel model)
        {
            if (ModelState.IsValid)
            {
                var screen = _multiplexFactory.PrepareSeatTypeModelToSeatType(model);
                _seatTypeService.InsertSeatType(screen);
                TempData["Success"] = "SeatType Added successfully...!";
                return RedirectToAction("SeatTypeList", new { ScreenId = model.ScreenId });
            }

            return View();
        }

        public ActionResult EditSeatType(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var seatType = _screenModelFactory.PrepareSeatTypeModelForEditEditSeatType(id);

            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");

            return View(seatType);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditSeatType(SeatTypeModel model)
        {
            if (ModelState.IsValid)
            {
                _screenModelFactory.PrepareSeatTypeForEditPost(model);
                TempData["Success"] = "SeatType Updated successfully...!";
                return RedirectToAction("SeatTypeList", new { ScreenId = model.ScreenId });
            }
            return View();
        }

        public ActionResult DeleteSeatType(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (Session["Id"] != null)
            {
                var Type = _seatTypeService.GetSeatTypeById(id);
                if (Type == null)
                {
                    return HttpNotFound();
                }
                _seatTypeService.DeleteSeatType(id);
                TempData["Success"] = "SeatType Deleted successfully...!";
                return RedirectToAction("SeatTypeList", new { ScreenId = Type.ScreenId });
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }
        #endregion

        #region Multiplex Base Movie
        public ActionResult MovieMultiplexList(int multiplexId)
        {
            var movie = _screenModelFactory.PrepareMovieMultiplexModelForList(multiplexId);
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            return View(movie);
        }
        public ActionResult AddMovie(int id)
        {
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            var movie = _screenModelFactory.PrepareMovieMultiplexModelForAddMovie(id);
            ViewBag.movie = new SelectList(_movieService.GetAllMovie().Where(X => X.IsDeleted == false), "Id", "Name");
            return View(movie);
        }

        [HttpPost]
        public ActionResult AddMovie(Movie_Multiplex_Model model)
        {
            if (ModelState.IsValid)
            {
                var movie = _multiplexFactory.PrepareMovieMultiplexModelToMovieMultiplex(model);
                _movieMultiplexServiece.InsertMovieMultiplex(movie);
                TempData["Success"] = "Movie Added successfully...!";
                return RedirectToAction("MovieMultiplexList", new { multiplexId = model.MultiplexId });
            }
            var movieList = _screenModelFactory.PrepareMovieMultiplexModelForAddMovie(model.MultiplexId);
            ViewBag.movie = new SelectList(_movieService.GetAllMovie().Where(X => X.IsDeleted == false), "Id", "Name");
            return View(movieList);
        }
        public ActionResult EditMovieMultiplex(int id)
        {
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            var movie = _screenModelFactory.PrepareMovieMultiplexModelForEditMovieMultiplex(id);
            ViewBag.movie = new SelectList(_movieService.GetAllMovie().Where(X => X.IsDeleted == false), "Id", "Name");
            return View(movie);
        }
        [HttpPost]
        public ActionResult EditMovieMultiplex(Movie_Multiplex_Model model)
        {

            if (ModelState.IsValid)
            {
                _screenModelFactory.PrepareMovieMultiplexForEditPost(model);
                TempData["Success"] = "Movie Updated successfully...!";
                return RedirectToAction("MovieMultiplexList", new { multiplexId = model.MultiplexId });
            }
            return View();
        }
        public ActionResult DeleteMovieMultiplex(int id)
        {
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            var movie = _movieMultiplexServiece.GetMovieMultiplexById(id);
            _movieMultiplexServiece.DeleteMovieMultiplex(id);
            TempData["AlertMessage"] = "Movie Deleted successfully...!";

Multiplex/Views/Screen/AddMovie.cshtml
@model Data.Models.Movie_Multiplex_Model

@{
    ViewBag.Title = "AddMoreMovie";
}


<h2 style=" font-size: 25px;">Add Movie >  @Html.DisplayFor(model => model.MultiplexName)</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        @Html.HiddenFor(x => x.MultiplexId)

        <div class="form-group">
            @Html.LabelFor(model => model.MultiplexName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MultiplexName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MovieName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MovieId", new SelectList(ViewBag.movie, "Value", "Text"), "Select Movie", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MovieName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
                <a href="@Url.Action("MovieMultiplexList","Screen",new {multiplexId = Model.MultiplexId})" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </div>
}

Multiplex/Views/Screen/CreateScreen.cshtml
@model Data.Models.ScreenModel

@{
    ViewBag.Title = "Create";
}

<h2 style=" font-size: 25px;">Add New Screen >  @Html.DisplayFor(model => model.MultiplexName)</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("_ScreenCreateOrUpdate", Model)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Screen" class="btn btn-default" />
                <a href="@Url.Action("ScreenList","Screen",new {multiplexId = Model.MultiplexId  })" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </div>
}

Multiplex/Views/Screen/CreateSeatType.cshtml
@model Data.Models.SeatTypeModel

@{
    ViewBag.Title = "CreateSeatType";
}

<h2>Add SeatType > @Html.DisplayFor(model => model.ScreenName) </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ScreenName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ScreenName)
                @Html.ValidationMessageFor(model => model.ScreenName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Seat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seat, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(x => x.ScreenId)


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <a href="@Url.Action("SeatTypeList","Screen",new {ScreenId = Model.ScreenId  })" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </div>
}

Multiplex/Views/Screen/CreateShow.cshtml
@model Data.Models.ShowModel

@{
    ViewBag.Title = "CreateShow";
}

<h2 style=" font-size: 25px;">Add New Show >  @Html.DisplayFor(model => model.MultiplexName)</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div id="datetimepicker1">

        </div>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Time, new { @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MultiplexName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-top:4px; font-size : 17px">
                @Model.MultiplexName
                @Html.ValidationMessageFor(model => model.MultiplexName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScreenName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ScreenId", new SelectList(ViewBag.Screen, "Value", "Text"), "Select Screen", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ScreenName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MovieId", new SelectList(Model.MovieList, "Value", "Text"), "Select Movie", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MovieName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" id="Languge_@Model.Id">
            @Html.LabelFor(model => model.LanguageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LanguageId", new SelectList(Model.LanguageList, "Value", "Text"), "Select Formate", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LanguageName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group" id="Formate_@Model.LanguageId">
            @Html.LabelFor(model => model.FormateName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FormateId", new SelectList(Model.FormateList, "Value", "Text"), "Select Formate", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FormateName, "", new { @class = "text-danger" })
            </div>
        </div>


        @Html.HiddenFor(x => x.MultiplexId)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
                <a href="@Url.Action("ShowList","Screen",new {multiplexId = Model.MultiplexId  })" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </div>

}



@*<script>
    window.onload = function () {
        //alert('Windows loaded ! ');
        //debugger
        $.ajax({
            type: "post",
            url: '/Home/GetScreen?multiplexId=' + $("#MultiplexId").val(),
            contentType: "html",
            success: function (response) {
                $("#ScreenId").empty();
                $("#ScreenId").append(response);
            }
        });
    };
</script>*@
<script src="~/Scripts/jquery-3.4.1.slim.min.js"></script>

<script>
    $(document).ready(function () {
        document.getElementById("Languge_@Model.Id").style.display ='none';
        document.getElementById("Formate_@Model.LanguageId").style.display ='none';
    })

    $("#MovieId").change(function () {
        //alert("111");
        //debugger
        $.ajax({
            type: "GET",
            url: '/Home/GetLanguage?movieId=' + $("#MovieId").val(),
            contentType: "html",
            success: function (response) {
                $("#LanguageId").html(response);
                  document.getElementById("Languge_@Model.Id").style.display = 'block';
            }
        });

        $.ajax({
            type: "GET",
            url: '/Home/GetFormate?movieId=' + $("#MovieId").val(),
            contentType: "html",
            success: function (response) {
                $("#FormateId").html(response);
                  document.getElementById("Formate_@Model.LanguageId").style.display = 'block';
            }
        });
    });
</script>



<script type="text/javascript">
    $(function () {
        $('.datepicker').datetimepicker({

            showTodayButton: true,
            showClose: true,
            minDate: new Date()
        });
       
    });
</script>

Multiplex/Views/Screen/MovieMultiplexList.cshtml
@*@model IEnumerable<Data.Models.Movie_Multiplex_Model>*@
@model Data.Models.ScreenListModel

@{
    ViewBag.Title = "MovieMultiplexList";
}

<div style="display:flex">
    <h3 style="margin-bottom: 20px;">

        Movie List >  @Html.DisplayFor(modelItem => Model.Name)
    </h3>
    <h3 style="margin-left: auto; font-size: 22px; margin-top: 18px; ">
        <a href="@Url.Action("AddMovie","Screen",new { id = Model.Id })" class="btn btn-default">Add New Movie</a>
    </h3>
</div>

<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MovieName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.movieMultiplexModelsList)
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.MovieName)
            </td>
            <td style="text-align: right;">
                <button>
                    @Html.ActionLink("Edit", "EditMovieMultiplex", new { id = item.Id }) 
                </button>
                <button>
                    @Html.ActionLink("Delete", "DeleteMovieMultiplex", new { id = item.Id }, new { onclick = "return confirm('You are sure wants to delete this Record?')" })
                </button>
            </td>
        </tr>
    }

</table>

<a href="@Url.Action("Index","Multiplex")" class="btn btn-default">Back</a>

Multiplex/Views/Screen/ScreenList.cshtml
@model Data.Models.ScreenListModel
@{
    ViewBag.Title = "Screen";
}

<div style="display:flex">
    <h3 style="margin-bottom: 20px;">

        Screen >  @Html.DisplayFor(modelItem => Model.Name)
    </h3>
    <h3 style="margin-left: auto; margin-top: 18px; ">
        <a href="@Url.Action("CreateScreen","Screen",new { id = Model.Id })" class="btn btn-default">Add New Screen</a>
    </h3>
</div>

<table class="table table-hover">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>
    @{
        int a = 0;
        int b = 0;

    }
    @foreach (var item in Model.screenModelsList)
    {


        <tr>


            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @{

                    if (item.Id != 0)
                    {
                        <div style="display: flex; justify-content: flex-end; ">
                            <div style="margin-right: 5px; ">
                                <button>
                                    @Html.ActionLink("Edit", "EditScreen", new { id = item.Id })
                                </button>

                            </div>

                            <div style="margin-right: 5px; ">
                                <button>
                                    @Html.ActionLink("Delete", "DeleteScreen", new { id = item.Id }, new { onclick = "return confirm('You are sure wants to delete this Record?')" })
                                </button>

                            </div>
                            <div>
                                <button>
                                    @Html.ActionLink("SeatType", "SeatTypeList", new { ScreenId = item.Id })
                                </button>
                            </div>
                        </div>

                    }

                }

            </td>
        </tr>
    }
</table>

<a href="@Url.Action("Index","Multiplex")" class="btn btn-default">Back</a>

Multiplex/Views/Screen/ShowList.cshtml
@*@model IEnumerable<Data.Models.ShowModel>*@
@model Data.Models.ScreenListModel
@{
    ViewBag.Title = "ShowList";
}

<div style="display:flex">
    <h3 style="margin-bottom: 20px;">

        Shows >  @Html.DisplayFor(modelItem => Model.Name)
    </h3>
    <h3 style="margin-left: auto; margin-top: 18px; ">
        <a href="@Url.Action("CreateShow","Screen",new { id = Model.Id })" class="btn btn-default">Add New Show</a>
    </h3>
</div>

<table class="table table-hover">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MultiplexName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScreenName)
        </th>
        <th>
            Language
            @*@Html.DisplayNameFor(model => model.LanguageName)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FormateName)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model.showModelList)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScreenName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LanguageName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.MovieName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FormateName)
            </td>
            <td style="text-align:right">
                @{
                    if (item.Time >= DateTime.Now)
                    {
                        <button>
                            @Html.ActionLink("Edit", "EditShow", new { id = item.Id })
                        </button>
                        <button>
                            @Html.ActionLink("Delete", "DeleteShow", new { id = item.Id }, new { onclick = "return confirm('You are sure wants to delete this Record?')" })
                        </button>
                        <button>
                            @Html.ActionLink("Seat","ShowPriceList",new { showId = item.Id})
                        </button>

                    }
                }


            </td>
        </tr>
    }

</table>
<a href="@Url.Action("Index","Multiplex")" class="btn btn-default">Back</a>
<script>
    setTimeout(function () {
        location.reload();
    }, 60000);
</script>