Multiplex/Controllers/CustomerController.cs
using Data.Context;
using Data.Models;
using Multiplex.Factory;
using Multiplex.Factory.ModelPrepare;
using PagedList;
using Repository;
using ServiceLayer;
using ServiceLayer.Dropdown;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Multiplex.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICityService _cityService;
        private readonly IStateService _stateSevice;
        private readonly ICustomerService _customerService;
        private readonly ICustomerModelFactory _customerModelFactory;
        private readonly IMultiplexFactory _multiplexFactory;

        public CustomerController(IMultiplexFactory multiplexFactory, ICustomerService customerService, ICustomerModelFactory customerModelFactory, IStateService stateSevice, ICityService cityService)
        {
            _cityService = cityService;
            _stateSevice = stateSevice;
            _customerService = customerService;
            _customerModelFactory = customerModelFactory;
            _multiplexFactory = multiplexFactory;
        }

        public ActionResult Index(string searchString, string currentFilter, int? page)
        {
            var customer = _customerModelFactory.PrepareCustomerModelForIndex(searchString, currentFilter,  page);
            ViewBag.CurrentFilter = searchString;
            if (Session["Id"] == null)
                return RedirectToAction("Login", "Home");
            return View(customer);
        }

        public ActionResult Create()
        {
            ViewBag.state = new SelectList(_stateSevice.GetAllState().Where(X => X.IsDeleted == false), "Id", "Name");
            ViewBag.city = new SelectList(_cityService.GetAllCities().Where(X => X.IsDeleted == false), "Id", "Name");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerModel model)
        {
            var customer = _customerService.GetCustomer();
            var customerlist = customer.Where(x => x.Email.Equals(model.Email)).FirstOrDefault();
            if (customerlist == null)
            {
                if (ModelState.IsValid)
                {
                    model.IsActive = true;
                    var cust = _multiplexFactory.PrepareCustomerModelToCustomer(model);
                    _customerService.InsertCustomer(cust);
                    TempData["Success"] = "Registration completed successfully. Now you can login with your Email..!";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Wrong"] = "This email already exist, Please try other mail type..!";
            }

            ViewBag.state = new SelectList(_stateSevice.GetAllState().Where(X => X.IsDeleted == false), "Id", "Name");
            ViewBag.city = new SelectList(_cityService.GetAllCities().Where(X => X.IsDeleted == false), "Id", "Name");
            return View(model);
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.state = new SelectList(_stateSevice.GetAllState().Where(X => X.IsDeleted == false), "Id", "Name");
            ViewBag.city = new SelectList(_cityService.GetAllCities().Where(X => X.IsDeleted == false), "Id", "Name");

            var customer = _customerModelFactory.PrepareCustomerModelForEdit(id);
            if (Session["Id"] != null)
            {
                return View(customer);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        [HttpPost]
        public ActionResult Edit(CustomerModel model)
        {
            if (ModelState.IsValid)
            {
                _customerModelFactory.PrepareCustomerModelForEditPost(model);
                TempData["Success"] = "User Updated successfully...!";
                return RedirectToAction("Index");
            }

            ViewBag.state = new SelectList(_stateSevice.GetAllState().Where(X => X.IsDeleted == false), "Id", "Name");
            ViewBag.city = new SelectList(_cityService.GetAllCities().Where(X => X.IsDeleted == false), "Id", "Name");
            var ct = _customerModelFactory.PrepareCustomerModelForEdit(model.Id);
            return View(ct);
        }

        public ActionResult Delete(int id)
        {

            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (Session["Id"] != null)
            {
                var customer = _customerService.GetCustomerById(id);

                if (customer == null)
                {
                    return HttpNotFound();
                }
                _customerService.DeleteCustomer(id);
                TempData["Success"] = "User Deleted successfully...!";
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }



    }
}

Multiplex/Views/Customer/Create.cshtml
@model Data.Models.CustomerModel

@{
    ViewBag.Title = "Create";
}

<h3>Customer > Register</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Confirmpassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Confirmpassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Confirmpassword, "", new { @class = "text-danger" })
            </div>
        </div>
        

        <div class="form-group">
            @Html.LabelFor(model => model.StateName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StateId", new SelectList(ViewBag.state, "Value", "Text"), "Select State", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityId", new SelectList(ViewBag.city, "Value", "Text"), "Select City", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <a href="@Url.Action("Index","Customer")" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $("#StateId").change(function () {
        var stateId = $(this).val();

        $.ajax({
            type: "post",
            url: '/Home/getCities?stateId=' + stateId,
            contentType: "html",
            success: function (response) {
                $("#CityId").empty();
                $("#CityId").append(response);
            }
        });
    });
</script>

Multiplex/Views/Customer/Edit.cshtml
@model Data.Models.CustomerModel

@{
    ViewBag.Title = "Edit";
}

<h2>Customer > Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" , @value = Model.Password} })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Confirmpassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Confirmpassword, new { htmlAttributes = new { @class = "form-control"} })
            @Html.ValidationMessageFor(model => model.Confirmpassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
            @Html.LabelFor(model => model.StateName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StateId", new SelectList(ViewBag.state, "Value", "Text"), "Select State", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityId", new SelectList(ViewBag.city, "Value", "Text"), "Select City", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
            </div>
        </div>
    <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
        </div>
        </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
            <a href="@Url.Action("Index","Customer")" class="btn btn-default">Cancel</a>

        </div>
    </div>
</div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
        $("#StateId").change(function () {
            /*alert("111");*/
            var stateId = $(this).val();

            $.ajax({
                type: "post",
                url: '/Home/getCities?stateId=' + stateId,
                contentType: "html",
                success: function (response) {
                    $("#CityId").empty();
                    $("#CityId").append(response);
                }
            });
        });
</script>

Multiplex/Views/Customer/Index.cshtml
@*@model IEnumerable<Data.Models.CustomerModel>*@
@model PagedList.IPagedList<Data.Models.CustomerModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<div style="display:flex">
    <h3 style="margin-bottom: 20px;">
        Customer List
    </h3>
    <h3 style="margin-left: auto; margin-top: 18px; ">
        <a href="@Url.Action("Create","Customer")" class="btn btn-default">Register New</a>
    </h3>
</div>

@using (Html.BeginForm("Index", "Customer", FormMethod.Get))
{
    <p>
        <b>Find by Name : </b> @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table table-hover">
    <tr>
        <th>
            Name
        </th>
        <th>
            Mobile No
        </th>
        <th>
            Email
        </th>
        <th>
            Password
        </th>
        <th>
            City
        </th>
        <th>
            State
        </th>
        <th>
            Active
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CityName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StateName)
            </td>
            <td @*class="active"*@>
                @Html.CheckBoxFor(modelItem => item.IsActive)
            </td>
            <td style="text-align:right">
                <button>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                </button>
                <button>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { onclick = "return confirm('You are sure wants to delete this Record?');" })
                </button>
            </td>
        </tr>
    }

</table>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, currentFilter = ViewBag.CurrentFilter }))
@*@section scripts
    {
    <script>
        $(document).ready(function () {

            $(".active").click(function () {
                window.location.href = "/Customer/Index";
            });
        })
    </script>
        }*@